package net.javaguids.lost_and_found.analytics;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

// Test suite for ActivityLog class. Tests log creation and data integrity
class ActivityLogTest {

    @Test
    void testConstructor() {
        String logId = "log-123";
        String userId = "user-456";
        String action = "LOGIN";
        String details = "User logged in successfully";

        ActivityLog log = new ActivityLog(logId, userId, action, details);

        assertEquals(logId, log.getLogId());
        assertEquals(userId, log.getUserId());
        assertEquals(action, log.getAction());
        assertEquals(details, log.getDetails());
        assertNotNull(log.getTimestamp());
    }

    @Test
    void testTimestampIsAutoGenerated() {
        LocalDateTime before = LocalDateTime.now();

        ActivityLog log = new ActivityLog("log-1", "user-1", "TEST", "Test action");

        LocalDateTime after = LocalDateTime.now();

        assertTrue(log.getTimestamp().isAfter(before) || log.getTimestamp().isEqual(before));
        assertTrue(log.getTimestamp().isBefore(after) || log.getTimestamp().isEqual(after));
    }

    @Test
    void testSetTimestamp() {
        ActivityLog log = new ActivityLog("log-1", "user-1", "TEST", "Test");
        LocalDateTime customTime = LocalDateTime.of(2025, 11, 20, 10, 30);

        log.setTimestamp(customTime);

        assertEquals(customTime, log.getTimestamp());
    }

    @Test
    void testGetters() {
        ActivityLog log = new ActivityLog("log-789", "user-abc", "REGISTER", "New user created");

        assertEquals("log-789", log.getLogId());
        assertEquals("user-abc", log.getUserId());
        assertEquals("REGISTER", log.getAction());
        assertEquals("New user created", log.getDetails());
    }

    @Test
    void testMultipleLogsHaveUniqueTimestamps() throws InterruptedException {
        ActivityLog log1 = new ActivityLog("log-1", "user-1", "ACTION1", "First");
        Thread.sleep(10); // Small delay to ensure different timestamps
        ActivityLog log2 = new ActivityLog("log-2", "user-2", "ACTION2", "Second");

        assertNotEquals(log1.getTimestamp(), log2.getTimestamp(),
                "Different logs should have different timestamps");
    }
}